### ISSUE TITLE
Smartwallet not working in Marketplace version + 1.5.0 not working

### ISSUE THREAD

**Issue by Walanors** [thirdweb-dev/unreal-sdk#12]
Hi!
When i tried the example coming from the Marketplace, the in-app wallet seems to work great, but the Guest and SmartWallet wasn't working at all, giving me (0x0000000000000000000000000000) adress 
I tried to use the 1.5.0 version from github but impossible to launch my project then:

```
1>ThirdwebInAppWalletHandle.cpp.obj : error LNK2019: unresolved external symbol in_app_wallet_verify_otp_email referenced in the function "public: __cdecl `public: void __cdecl FInAppWalletHandle::SignInWithOTP(class FString const &,class TDelegate<void __cdecl(void),struct FDefaultDelegateUserPolicy> const &,class TDelegate<void __cdecl(class FString const &),struct FDefaultDelegateUserPolicy> const &)'::`2'::<lambda_1>::operator()(void)const " (??R<lambda_1>@?1??SignInWithOTP@FInAppWalletHandle@@QEAAXAEBVFString@@AEBV?$TDelegate@$$A6AXXZUFDefaultDelegateUserPolicy@@@@AEBV?$TDelegate@$$A6AXAEBVFString@@@ZUFDefaultDelegateUserPolicy@@@@@Z@QEBA@XZ)

1>ThirdwebInAppWalletHandle.cpp.obj : error LNK2019: unresolved external symbol in_app_wallet_verify_otp_phone referenced in the function "public: __cdecl `public: void __cdecl FInAppWalletHandle::SignInWithOTP(class FString const &,class TDelegate<void __cdecl(void),struct FDefaultDelegateUserPolicy> const &,class TDelegate<void __cdecl(class FString const &),struct FDefaultDelegateUserPolicy> const &)'::`2'::<lambda_1>::operator()(void)const " (??R<lambda_1>@?1??SignInWithOTP@FInAppWalletHandle@@QEAAXAEBVFString@@AEBV?$TDelegate@$$A6AXXZUFDefaultDelegateUserPolicy@@@@AEBV?$TDelegate@$$A6AXAEBVFString@@@ZUFDefaultDelegateUserPolicy@@@@@Z@QEBA@XZ)

1>ThirdwebInAppWalletHandle.cpp.obj : error LNK2019: unresolved external symbol ecosystem_wallet_verify_otp_email referenced in the function "public: __cdecl `public: void __cdecl FInAppWalletHandle::LinkOTP(struct FInAppWalletHandle const &,class FString const &,class TDelegate<void __cdecl(void),struct FDefaultDelegateUserPolicy> const &,class TDelegate<void __cdecl(class FString const &),struct FDefaultDelegateUserPolicy> const &)'::`2'::<lambda_1>::operator()(void)const " (??R<lambda_1>@?1??LinkOTP@FInAppWalletHandle@@QEAAXAEBU2@AEBVFString@@AEBV?$TDelegate@$$A6AXXZUFDefaultDelegateUserPolicy@@@@AEBV?$TDelegate@$$A6AXAEBVFString@@@ZUFDefaultDelegateUserPolicy@@@@@Z@QEBA@XZ)

1>ThirdwebInAppWalletHandle.cpp.obj : error LNK2019: unresolved external symbol ecosystem_wallet_verify_otp_phone referenced in the function "public: __cdecl `public: void __cdecl FInAppWalletHandle::SignInWithOTP(class FString const &,class TDelegate<void __cdecl(void),struct FDefaultDelegateUserPolicy> const &,class TDelegate<void __cdecl(class FString const &),struct FDefaultDelegateUserPolicy> const &)'::`2'::<lambda_1>::operator()(void)const " (??R<lambda_1>@?1??SignInWithOTP@FInAppWalletHandle@@QEAAXAEBVFString@@AEBV?$TDelegate@$$A6AXXZUFDefaultDelegateUserPolicy@@@@AEBV?$TDelegate@$$A6AXAEBVFString@@@ZUFDefaultDelegateUserPolicy@@@@@Z@QEBA@XZ)
```

**Comment by dirtycajunrice** [comment]
@Walanors Hey This is fixed in 1.6.0

**Comment by dirtycajunrice** [comment]
Fixed in #13
